/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactItem: typeof import('./components/ContactItem.vue')['default']
    GlobalFooter: typeof import('./components/global/GlobalFooter.vue')['default']
    GlobalHeader: typeof import('./components/global/GlobalHeader.vue')['default']
    ImageCard: typeof import('./components/ImageCard.vue')['default']
    NewsCard: typeof import('./components/NewsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./components/SectionTitle.vue')['default']
    TeacherCard: typeof import('./components/TeacherCard.vue')['default']
  }
}
